/*
 * [한국어 설명] 중복 제거(deduplication) 버퍼 관리 (dedupe.c)
 *
 * === 파일의 역할 ===
 * fio의 중복 제거 워킹셋 시드를 초기화하는 기능을 담당한다. 중복 제거 모드에서는
 * 특정 비율의 I/O가 동일 데이터 패턴을 사용하여 스토리지 중복 제거 성능을 테스트.
 *
 * === 전체 아키텍처에서의 위치 ===
 * init.c의 add_job()에서 init_dedupe_working_set_seeds()를 호출.
 * 호출 체인: add_job() [init.c] → init_dedupe_working_set_seeds() [이 파일]
 *
 * === 타 모듈과의 연결 ===
 * - init.c: add_job()에서 중복 제거 시드 초기화
 * - dedupe.h: API 선언
 * - io_u.c: I/O 버퍼 채울 때 중복 제거 시드 참조
 *
 * === 주요 함수/구조체 요약 ===
 * - init_global_dedupe_working_set_seeds(): 전역 중복 제거 시드 초기화
 * - init_dedupe_working_set_seeds(): 작업별 워킹셋 시드 초기화
 */

#include "fio.h"  /* fio 핵심 구조체 및 매크로 */

/**
 * initializes the global dedup workset.
 * this needs to be called after all jobs' seeds
 * have been initialized
 */
/* [한국어] 전역 중복 제거 워킹셋 시드 초기화
 * 모든 작업의 시드가 초기화된 후에 호출되어야 한다.
 * dedupe_global 옵션이 켜진 모든 작업에 대해 워킹셋 시드를 설정 */
int init_global_dedupe_working_set_seeds(void)
{
	for_each_td(td) {
		if (!td->o.dedupe_global)
			continue;

		if (init_dedupe_working_set_seeds(td, 1))
			return 1;
	} end_for_each();

	return 0;
}

/* [한국어] 작업별 중복 제거 워킹셋 시드 초기화
 * - dedupe_percentage와 DEDUPE_MODE_WORKING_SET이 설정된 경우에만 동작
 * - 고유 페이지 수 = (파일크기 * 워킹셋비율) / 최소블록크기
 * - 각 고유 페이지에 대해 buf_state에서 파생된 난수 시드를 저장
 * - 압축(compress) 사용 시 시드를 여러 번 진행하여 동일 버퍼 재현 가능
 * - 전역 중복 제거(global_dedup) 시 여러 작업 간 시드를 로테이션하여
 *   동일 데이터가 다른 작업에서도 생성되도록 함
 *
 * @td: 스레드 데이터
 * @global_dedup: 전역 중복 제거 여부 (true면 작업 간 시드 공유) */
int init_dedupe_working_set_seeds(struct thread_data *td, bool global_dedup)
{
	int tindex;
	struct thread_data *td_seed;
	unsigned long long i, j, num_seed_advancements, pages_per_seed;
	struct frand_state dedupe_working_set_state = {0};

	if (!td->o.dedupe_percentage || !(td->o.dedupe_mode == DEDUPE_MODE_WORKING_SET))
		return 0;

	tindex = td->thread_number - 1;
	/* [한국어] 시드 진행 횟수 = 최소 쓰기 블록 크기 / 압축 청크 크기
	 * 압축 사용 시 하나의 블록이 여러 번의 시드 진행을 필요로 함 */
	num_seed_advancements = td->o.min_bs[DDIR_WRITE] /
		min_not_zero(td->o.min_bs[DDIR_WRITE], (unsigned long long) td->o.compress_chunk);
	/*
	 * The dedupe working set keeps seeds of unique data (generated by buf_state).
	 * Dedupe-ed pages will be generated using those seeds.
	 */
	/* [한국어] 고유 페이지 수 계산: 전체 크기 * 워킹셋 비율 / 블록 크기 */
	td->num_unique_pages = (td->o.size * (unsigned long long)td->o.dedupe_working_set_percentage / 100) / td->o.min_bs[DDIR_WRITE];
	/* [한국어] 각 고유 페이지에 대한 난수 상태를 저장할 배열 할당 */
	td->dedupe_working_set_states = malloc(sizeof(struct frand_state) * td->num_unique_pages);
	if (!td->dedupe_working_set_states) {
		log_err("fio: could not allocate dedupe working set\n");
		return 1;
	}

	/* [한국어] 첫 번째 시드는 버퍼 상태(buf_state)에서 직접 복사 */
	frand_copy(&dedupe_working_set_state, &td->buf_state);
	frand_copy(&td->dedupe_working_set_states[0], &dedupe_working_set_state);
	/* [한국어] 전역 중복 제거 시 작업당 시드 수 (균등 분배) */
	pages_per_seed = max(td->num_unique_pages / thread_number, 1ull);
	for (i = 1; i < td->num_unique_pages; i++) {
		/*
		 * When compression is used the seed is advanced multiple times to
		 * generate the buffer. We want to regenerate the same buffer when
		 * deduping against this page
		 */
		/* [한국어] 압축 사용 시 시드를 여러 번 진행하여 동일 버퍼를 재현할 수 있게 함 */
		for (j = 0; j < num_seed_advancements; j++)
			__get_next_seed(&dedupe_working_set_state);

		/*
		 * When global dedup is used, we rotate the seeds to allow
		 * generating same buffers across different jobs. Deduplication buffers
		 * are spread evenly across jobs participating in global dedupe
		 */
		/* [한국어] 전역 중복 제거 시 pages_per_seed마다 다음 작업의 시드로 전환
		 * 이를 통해 서로 다른 작업에서 동일한 데이터 블록이 생성됨 */
		if (global_dedup && i % pages_per_seed == 0) {
			td_seed = tnumber_to_td(++tindex % thread_number);
			frand_copy(&dedupe_working_set_state, &td_seed->buf_state);
		}

		frand_copy(&td->dedupe_working_set_states[i], &dedupe_working_set_state);
	}

	return 0;
}
